/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zeus_prj;

import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class FrmMascotas extends javax.swing.JFrame {
    //Almacenamiento
    int TAM = 100;
    ClsMascotas [] arreMas = new ClsMascotas[TAM];
    int cantMas = 0;
    int posicion = -1;
    
    /**
     * Creates new form FrmMascotas
     */
    public FrmMascotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtApodo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRaza = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        cboSexo = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRegistrados = new javax.swing.JTable();
        txtNombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Registra tu mascota");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 50);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("Identificación:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 60, 90, 10);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("Apodo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 60, 40, 15);

        txtIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdentificacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtIdentificacion);
        txtIdentificacion.setBounds(10, 90, 110, 30);

        txtApodo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtApodo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtApodo);
        txtApodo.setBounds(150, 90, 110, 30);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("Sexo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 140, 70, 20);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("Raza:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 140, 50, 15);

        txtRaza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtRaza.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtRaza);
        txtRaza.setBounds(10, 170, 110, 30);

        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zeus_prj/imagenes/icons8_clear_formatting_40px.png"))); // NOI18N
        btnLimpiar.setBorder(null);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(20, 240, 50, 40);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zeus_prj/imagenes/icons8_save_40px.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(90, 240, 50, 40);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zeus_prj/imagenes/icons8_search_40px.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(170, 240, 50, 40);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zeus_prj/imagenes/icons8_edit_property_40px.png"))); // NOI18N
        btnModificar.setBorder(null);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(240, 240, 50, 40);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zeus_prj/imagenes/icons8_waste_40px.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(320, 240, 50, 40);

        cboSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Hembra" }));
        cboSexo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSexoActionPerformed(evt);
            }
        });
        getContentPane().add(cboSexo);
        cboSexo.setBounds(300, 170, 100, 30);

        tblRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación", "Apodo", "Nombres", "Raza", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRegistrados.getTableHeader().setReorderingAllowed(false);
        tblRegistrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistradosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblRegistrados);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 290, 390, 160);

        txtNombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombres.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtNombres);
        txtNombres.setBounds(170, 170, 100, 30);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("Nombres:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 140, 80, 15);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zeus_prj/imagenes/icons8_exit_40px.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(300, 70, 60, 40);

        setBounds(0, 0, 420, 492);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSexoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblRegistradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistradosMouseClicked
     pasarDatos( evt );
    }//GEN-LAST:event_tblRegistradosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMascotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblRegistrados;
    private javax.swing.JTextField txtApodo;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        this.txtIdentificacion.setText("");
        this.txtApodo.setText("");
        this.txtNombres.setText("");
        this.txtRaza.setText("");
        this.cboSexo.setSelectedItem("Macho");
        
        llenarRegistrados();
        posicion = -1;
        
        this.txtIdentificacion.grabFocus();
    }

    private void Guardar() {
       ClsMascotas mas = new ClsMascotas();
       
       mas.identificacion = Integer.parseInt(this.txtIdentificacion.getText().trim());
       mas.apodo = this.txtApodo.getText().trim().toUpperCase();
       mas.nombres = this.txtNombres.getText().trim().toUpperCase();
       mas.raza = this.txtRaza.getText().trim().toUpperCase();
       mas.sexo = this.cboSexo.getSelectedItem().toString();
     
       
       //Si tengo espacios en el arreglo para el nuevo registro
       if (cantMas < TAM){
           arreMas[cantMas] = mas;
           cantMas++;
           //Limpiar Controlar
           Limpiar();
       }else{
           JOptionPane.showMessageDialog(this, "No hay espacios");
       }
       
   }

    private void llenarRegistrados() {
        DefaultTableModel modelo = (DefaultTableModel) this.tblRegistrados.getModel();
        
        //Limpiar la tabla
        modelo.getDataVector().clear();
        //Recorrer el arreglo unidimensional
        for (int i = 0; i < cantMas; i++) {
            //Obtener cada Mascota almacenada en el arreglo
            ClsMascotas x = arreMas[i];
            
            ArrayList array = new ArrayList();
            array.add( x.identificacion);
            array.add( x.apodo);
            array.add( x.nombres);
            array.add( x.raza);
            array.add( x.sexo);
            
            modelo.addRow( array.toArray() );
            
        }
    }

    private void Buscar() {
        int id = Integer.parseInt(this.txtIdentificacion.getText().trim());
        
        posicion = -1;
        for (int i = 0; i < cantMas; i++) {
            ClsMascotas x = arreMas[i];
            
            if ( x.identificacion == id ) {
                this.txtNombres.setText( x.nombres );
                this.txtApodo.setText( x.apodo );
                this.txtRaza.setText( x.raza );
                this.cboSexo.setSelectedItem( x.sexo );
                posicion = i;
                this.txtIdentificacion.grabFocus();
                break;
            }
        }
        if (posicion == -1) {
            JOptionPane.showMessageDialog(this,"No está registrado");            
        }
    }

    private void pasarDatos(MouseEvent e ) {
        if (e.getSource() == this.tblRegistrados) {
            if (e.getClickCount() == 2) {
                int fila = this.tblRegistrados.getSelectedRow();
                
                if (fila > -1) {
                  this.txtIdentificacion.setText( this.tblRegistrados.getValueAt(fila, 0).toString() );  
                  this.txtApodo.setText( this.tblRegistrados.getValueAt(fila, 1).toString() );
                  this.txtNombres.setText( this.tblRegistrados.getValueAt(fila, 2).toString() );
                  this.txtRaza.setText( this.tblRegistrados.getValueAt(fila, 3).toString() );
                  this.cboSexo.setSelectedItem(this.tblRegistrados.getValueAt(fila, 4).toString() );
                }
                posicion = fila;
                this.txtIdentificacion.grabFocus();
            }
            
        }
        
    }

    private void Modificar() {
    
       //la posicion es valida
       if (posicion != -1 ){
       ClsMascotas mas = new ClsMascotas();
       mas.identificacion = Integer.parseInt(this.txtIdentificacion.getText().trim());
       mas.apodo = this.txtApodo.getText().trim();
       mas.nombres = this.txtNombres.getText().trim().toUpperCase();
       mas.raza = this.txtRaza.getText().trim().toUpperCase();
       mas.sexo = this.cboSexo.getSelectedItem().toString();
           
        arreMas[posicion] = mas;
        //Limpiar Controlar
        Limpiar();
           
       }else{
           JOptionPane.showMessageDialog(this, "No ha buscado o seleccionado de la tabla registrados.");
       }
        
    }

    private void Eliminar() {
        
        if ( posicion != -1) {
            int opcion =  JOptionPane.showConfirmDialog(this, "¿Desea Eliminar el registro?", "Eliminacion", JOptionPane.YES_NO_OPTION);
            
            if (opcion == JOptionPane.YES_OPTION) {
                for (int i = posicion; i < (cantMas -1); i++) {
                    arreMas[i]= arreMas[i + 1];
                }
                cantMas--;
                JOptionPane.showMessageDialog(this, "Elemento Eliminado");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Posicion No Válida");
        }
    }
}
